[package]
name = "rustual-boy-libretro"
version = "0.1.0"
authors = ["Sebastian Reinhard <sebastian@sebbert.me>"]

[dependencies]
libc = "0.2.*"
log = "0.3.*"
bitflags = "0.7.*"

[dependencies.rustual-boy]
path="../rustual-boy"